machine:
  install:
    disk: /dev/nvme0n1
  disks:
    - device: /dev/nvme0n1
      wipeTable: true
      partitions:
        - mountpoint: /var/mnt/local-path-provisioner
          size: 322122547200 # 300 GiB

---
apiVersion: v1alpha1
kind: VolumeConfig
name: EPHEMERAL
provisioning:
  maxSize: 40GiB
