---
name: Validate

on:
  pull_request:
    branches:
    - main

permissions:
  contents: read

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # 7.0.1

#      - name: Lint YAML
#        uses: ibiqlik/action-yamllint@2576378a8e339169678f9939646ee3ee325e845c # 3.1.1

#      - name: Setup Flux CLI 
#        uses: fluxcd/flux2/action@889be9d6cc8afa8ed639e1e1ba4ab678e3b38d8c # 2.9.4

#      - name: Validate Flux and Kubernetes manifests 
#        run: flux schema validate ./clusters/yggdrasil --skip-missing-schemas

      - name: Build Flux manifests
        run: kubectl kustomize ./clusters/yggdrasil/flux-system

      - name: Build Cilium manifests
        run: kubectl kustomize ./infrastructure/cilium

